language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn install
  - yarn build
  - cp CNAME ./build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
    branch: master
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
